### ISSUE TITLE
请问这个汉化包支持mac电脑吗？

### ISSUE THREAD

**Issue by tomoya92** [mistzzt/L_Instructions#2]
我把包里的内容都解压复制到mac游戏对应的目录下，然后把L.exe，L 分别改成了 Terraria.exe，Terraria 运行游戏，秒退，不知道是不支持还是我改的地方不对，求解！

**Comment by mistzzt** [comment]
汉化程序在初始化的时候会报错…… 我试过

应该是混淆程序造成的问题，以后会修复

所以现在就不支持osx系统了， linux同理

**Comment by tomoya92** [comment]
知道了，大概什么时候能修好呢？透露个大致的时间呗！

**Comment by mistzzt** [comment]
嘛…我去问问作者，看看他什么时候有空解决。

稍后回复
